spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/meal_time_tinder
        username: mtt
    jpa:
        hibernate:
            # Only for developing purpose - change value to none for production
            ddl-auto: update
    web:
        resources:
            static-locations: file:/Users/michaelclark/Library/CloudStorage/OneDrive-UniversityofStAndrews/St Andrews - CS MSc/CS5031 Software Engineering Practice/thur6/project-code/images
